/* ============================================================
   ROMERO JOYERÍA — CATÁLOGO
   ------------------------------------------------------------
   Generado desde el panel el 18 de septiembre de 2026 a las 11:37 p. m..
   Se puede editar a mano igual: es un archivo común.

   categoria: "todos" | "anillos" | "sets" | "dijes" | "cadenas" | "aros"

   stock:     unidades disponibles. Sin el campo, la pieza se
              vende sin control. 0 es agotado y 3 o menos
              muestra "Últimas unidades".
   ============================================================ */

const CATEGORIAS = [
  { id: "todos", nombre: "Todo", desc: "La colección completa" },
  { id: "anillos", nombre: "Anillos", desc: "Sellos, marcos y solitarios en plata 925" },
  { id: "sets", nombre: "Sets", desc: "Cadena, dije, aros y anillo a juego, en su estuche" },
  { id: "dijes", nombre: "Dijes", desc: "Colgantes sueltos para armar tu cadena" },
  { id: "cadenas", nombre: "Cadenas", desc: "Cadenas de plata con dije incluido" },
  { id: "aros", nombre: "Aros", desc: "Aros de abroche a presión" },
];

const PRODUCTOS = [

  /* ---------------- ANILLOS ---------------- */
  {
    id: "anillo-01",
    nombre: "Anillo Bvlgari",
    categoria: "anillos",
    precio: 18500,
    img: "img/productos/anillo-01.jpg",
    material: "Plata 925 con terminación dorada",
    desc: "Marco circular grabado alrededor de una piedra central facetada. El modelo más pedido de la casa.",
    piedras: ["Cristal", "Rosa", "Granate"],
  },
  {
    id: "anillo-02",
    nombre: "Anillo Quadra Bvlgari",
    categoria: "anillos",
    precio: 18500,
    img: "img/productos/anillo-02.jpg",
    material: "Plata 925 con terminación dorada",
    desc: "Marco cuadrado de canto ancho con piedra talla princesa. Base sólida, cómodo de usar todo el día.",
    piedras: ["Rosa", "Azul", "Verde", "Violeta"],
  },
  {
    id: "anillo-03",
    nombre: "Anillo Quadra Fino",
    categoria: "anillos",
    precio: 16900,
    img: "img/productos/anillo-03.jpg",
    material: "Plata 925 con terminación dorada",
    desc: "La versión liviana del Quadra: mismo frente cuadrado sobre una banda más delgada. Ideal para combinar de a dos.",
    piedras: ["Verde", "Granate", "Rosa", "Cristal", "Negro"],
  },
  {
    id: "anillo-04",
    nombre: "Anillo Fino Bvlgari",
    categoria: "anillos",
    precio: 16900,
    img: "img/productos/anillo-04.jpg",
    material: "Plata 925 con terminación dorada",
    desc: "Frente circular sobre banda delgada. El más discreto de la línea, pensado para uso diario.",
    piedras: ["Cristal", "Rosa", "Dorado"],
  },
  {
    id: "anillo-05",
    nombre: "Anillo Sello Plata",
    categoria: "anillos",
    precio: 21900,
    img: "img/productos/anillo-05.jpg",
    material: "Plata 925",
    desc: "Sello redondo con frente labrado, sin piedra. Plata pulida sin baño, para quien prefiere el tono frío.",
    piedras: [],
  },
  {
    id: "anillo-06",
    nombre: "Anillo Bvlgari Quadra Color",
    categoria: "anillos",
    precio: 18500,
    img: "img/productos/anillo-06.jpg",
    material: "Plata 925 con terminación dorada",
    desc: "El Quadra en toda su carta de piedras. Elegí el color al hacer el pedido.",
    piedras: ["Cristal", "Turquesa", "Verde", "Violeta", "Granate", "Negro", "Ámbar"],
    etiqueta: "Selección",
  },
  {
    id: "anillo-07",
    nombre: "Anillo Bvlgari Color",
    categoria: "anillos",
    precio: 18500,
    img: "img/productos/anillo-07.jpg",
    material: "Plata 925 con terminación dorada",
    desc: "El Aura en toda su carta de piedras, del turquesa al negro profundo.",
    piedras: ["Cristal", "Blanco", "Rosa", "Azul", "Turquesa", "Verde", "Violeta"],
  },
  {
    id: "anillo-08",
    nombre: "Anillo Bvlgari Grueso",
    categoria: "anillos",
    precio: 19900,
    img: "img/productos/anillo-08.jpg",
    material: "Plata 925 con terminación dorada",
    desc: "Los flancos llevan estrías talladas que acompañan la curva del dedo y hacen que la pieza tome más luz.",
    piedras: ["Cristal", "Rosa", "Azul", "Granate", "Negro"],
  },
  {
    id: "anillo-09",
    nombre: "Anillo Bvlgari Sello Quadra",
    categoria: "anillos",
    precio: 23900,
    img: "img/productos/anillo-09.jpg",
    material: "Plata 925 con terminación dorada",
    desc: "El de mayor cuerpo del catálogo: frente cuadrado amplio sobre banda gruesa. Se usa solo, sin acompañantes.",
    piedras: ["Rosa", "Azul", "Turquesa", "Violeta", "Granate", "Negro"],
  },
  {
    id: "anillo-10",
    nombre: "Anillo Marquise Bvlgari",
    categoria: "anillos",
    precio: 20900,
    img: "img/productos/anillo-10.jpg",
    material: "Plata 925 con terminación dorada",
    desc: "Frente en forma de ojo, alargado sobre el dedo. La silueta más distinta de la colección.",
    piedras: ["Cristal", "Rosa", "Violeta", "Ámbar"],
  },

  /* ---------------- SETS ---------------- */
  {
    id: "set-01",
    nombre: "Set Bvlgari Rosa",
    categoria: "sets",
    precio: 46900,
    img: "img/productos/set-01.jpg",
    material: "Plata 925 con terminación dorada",
    desc: "Cadena con dije, aros y anillo a juego, en piedra rosa. Viene en estuche, listo para regalar.",
    piezas: ["Cadena con dije", "Aros", "Anillo"],
    piedras: [],
  },
  {
    id: "set-02",
    nombre: "Set Bvlgari Violeta",
    categoria: "sets",
    precio: 46900,
    img: "img/productos/set-02.jpg",
    material: "Plata 925 con terminación dorada",
    desc: "Las tres piezas del Aura en amatista. Cadena eslabón figaro y estuche incluido.",
    piezas: ["Cadena con dije", "Aros", "Anillo"],
    piedras: [],
  },
  {
    id: "set-03",
    nombre: "Set Bvlgari Azul",
    categoria: "sets",
    precio: 46900,
    img: "img/productos/set-03.jpg",
    material: "Plata 925 con terminación dorada",
    desc: "Piedra azul profunda sobre cadena fina. El contraste más marcado de la línea.",
    piezas: ["Cadena con dije", "Aros", "Anillo"],
    piedras: [],
  },
  {
    id: "set-04",
    nombre: "Set Bvlgari Quadra Cristal",
    categoria: "sets",
    precio: 44900,
    img: "img/productos/set-04.jpg",
    material: "Plata 925 con terminación dorada",
    desc: "Dije cuadrado y anillo a juego en piedra cristal. Dos piezas, en estuche.",
    piezas: ["Cadena con dije", "Anillo"],
    piedras: [],
  },
  {
    id: "set-05",
    nombre: "Set Bvlgari Verde",
    categoria: "sets",
    precio: 46900,
    img: "img/productos/set-05.jpg",
    material: "Plata 925 con terminación dorada",
    desc: "Verde esmeralda en las tres piezas, sobre cadena figaro. Uno de los más elegidos para regalo.",
    piezas: ["Cadena con dije", "Aros", "Anillo"],
    piedras: [],
  },
  {
    id: "set-06",
    nombre: "Set Bvlgari Ámbar",
    categoria: "sets",
    precio: 46900,
    img: "img/productos/set-06.jpg",
    material: "Plata 925 con terminación dorada",
    desc: "Piedra ámbar cálida sobre cadena fina de plata. El tono más suave del catálogo.",
    piezas: ["Cadena con dije", "Aros", "Anillo"],
    piedras: [],
  },
  {
    id: "set-07",
    nombre: "Set Bvlgari Quadra Granate",
    categoria: "sets",
    precio: 46900,
    img: "img/productos/set-07.jpg",
    material: "Plata 925 con terminación dorada",
    desc: "Rojo granate en marco cuadrado, las tres piezas a juego dentro del estuche.",
    piezas: ["Cadena con dije", "Aros", "Anillo"],
    piedras: [],
  },
  {
    id: "set-08",
    nombre: "Set Bvlgari Quadra Azul",
    categoria: "sets",
    precio: 46900,
    img: "img/productos/set-08.jpg",
    material: "Plata 925 con terminación dorada",
    desc: "Dije y aros cuadrados en azul noche, sobre cadena eslabón figaro.",
    piezas: ["Cadena con dije", "Aros"],
    piedras: [],
  },
  {
    id: "set-09",
    nombre: "Set Bvlgari Quadra Rosa",
    categoria: "sets",
    precio: 44900,
    img: "img/productos/set-09.jpg",
    material: "Plata 925 con terminación dorada",
    desc: "Cadena con dije cuadrado rosa y anillo a juego. Dos piezas, en estuche.",
    piezas: ["Cadena con dije", "Anillo"],
    piedras: [],
  },
  {
    id: "set-10",
    nombre: "Set Barra Azul",
    categoria: "sets",
    precio: 48900,
    img: "img/productos/set-10.jpg",
    material: "Plata 925 con terminación dorada",
    desc: "Dije rectangular de dos barras en azul, con aros a juego. La pieza de mayor tamaño del catálogo.",
    piezas: ["Cadena con dije", "Aros"],
    piedras: [],
    etiqueta: "Selección",
  },

  /* ---------------- DIJES ---------------- */
  {
    id: "dije-01",
    nombre: "Dije Bvlgari Quadra",
    categoria: "dijes",
    precio: 12900,
    img: "img/productos/dije-01.jpg",
    material: "Plata 925 con terminación dorada",
    desc: "Colgante cuadrado suelto, sin cadena. Entra en cualquier cadena fina. Elegí el color de la piedra.",
    piedras: ["Cristal", "Rosa", "Azul", "Verde", "Granate", "Negro"],
  },
  {
    id: "dije-02",
    nombre: "Dije Bvlgari",
    categoria: "dijes",
    precio: 12900,
    img: "img/productos/dije-02.jpg",
    material: "Plata 925 con terminación dorada",
    desc: "Colgante circular suelto en tres tamaños, del más chico al más marcado.",
    piedras: ["Cristal", "Rosa", "Granate"],
  },
  {
    id: "dije-03",
    nombre: "Dije Bvlgari Quadra Mini",
    categoria: "dijes",
    precio: 10900,
    img: "img/productos/dije-03.jpg",
    material: "Plata 925 con terminación dorada",
    desc: "La versión chica del Quadra, para usar de a varios en la misma cadena o de a uno bien discreto.",
    piedras: ["Cristal", "Blanco", "Rosa", "Azul", "Verde", "Violeta", "Granate", "Negro"],
  },

  /* ---------------- CADENAS ---------------- */
  {
    id: "cadena-01",
    nombre: "Cadena con Dije Bvlgari",
    categoria: "cadenas",
    precio: 27900,
    img: "img/productos/cadena-01.jpg",
    material: "Plata 925, dije con terminación dorada",
    desc: "Cadena de plata tejido trenzado con dije circular incluido. Largo 45 cm.",
    piedras: ["Cristal", "Rosa", "Granate", "Negro"],
  },
  {
    id: "cadena-02",
    nombre: "Cadena Trenzada con Dije Bvlgari",
    categoria: "cadenas",
    precio: 27900,
    img: "img/productos/cadena-02.jpg",
    material: "Plata 925, dije con terminación dorada",
    desc: "El mismo tejido en cuatro largos, de 40 a 55 cm, para superponer varias a distinta altura.",
    piedras: ["Cristal", "Rosa", "Granate", "Negro"],
    etiqueta: "Selección",
  },
  {
    id: "cadena-03",
    nombre: "Cadena con Dije Bvlgari Quadra",
    categoria: "cadenas",
    precio: 27900,
    img: "img/productos/cadena-03.jpg",
    material: "Plata 925, dije con terminación dorada",
    desc: "Cadena de plata con dije cuadrado incluido. Largo 45 cm.",
    piedras: ["Cristal", "Granate", "Negro"],
  },

  /* ---------------- AROS ---------------- */
  {
    id: "aro-01",
    nombre: "Aros Bvlgari y Quadra",
    categoria: "aros",
    precio: 14900,
    img: "img/productos/aro-01.jpg",
    material: "Plata 925 con terminación dorada",
    desc: "Aros de abroche a presión, en marco redondo o cuadrado. Toda la carta de piedras disponible.",
    piedras: ["Cristal", "Rosa", "Azul", "Turquesa", "Verde", "Violeta", "Granate", "Negro", "Ámbar"],
  },

];
